### PR TITLE
Feature/test example

### PR DESCRIPTION
**Pull request by leo8198**
Unit test to test if the examples work using the pytest package.

I plan to add more examples in another PR.

### CODE REVIEW

**Comment by lorey** [comment]
Hi @leo8198, thank you very much for the Pull Request. That's a very good idea and a very welcome addition!

**Comment by leo8198** [comment]
Thank you, @lorey !

**Comment by lorey** [comment]
Just a small side note: I'm not sure if you saw the tox/pre-commit configuration. It automatically takes care of testing and formatting for you. The easiest way is to install and run `tox` as described in [CONTRIBUTING.md](CONTRIBUTING.md) before committing changes.

If you need help with your next PR, feel free to drop me a mail, I'll help :)

**Comment by leo8198** [comment]
Yes, I ran the `tox` command after I finished my code changes and before sending the PR. Fascinating tool!

It didn't work correctly?

Thanks for the side note!

**Comment by lorey** [comment]
No, running tox could not work. This is because the example uses requests which is not a dependency of mlscraper, so in an isolated environment, this should not work by design. Check out the commits after your PR to see how I fixed it. But no worries, just some small additions 😄

**Comment by leo8198** [comment]
Alright, thanks for the clarifications!

**Pull request merged**
